name: Endor Labs
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '29 14 * * 2'
jobs:
  build-and-scan:
    permissions:
      id-token: write # Write permission is required to request a json web token (JWT) to perform keyless authentication
      contents: read  # Required by actions/checkout@v3 to checkout a private repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build artifact
        run: npm ci && npm run build

      # For pull requests
      - name: Endor Labs scan (pull request)
        if: github.event_name == 'pull_request'
        uses: endorlabs/github-action@b51bd06466b545f01a6ac788e3e1147695d3936c
        with:
          namespace: "endor-solutions-jcastaneda"
          sarif_file: findings.sarif

      # For pushes to main
      - name: Endor Labs scan (monitor)
        if: github.event_name == 'push'
        uses: endorlabs/github-action@b51bd06466b545f01a6ac788e3e1147695d3936c
        with:
          namespace: "endor-solutions-jcastaneda"
          ci_run: "false"
          sarif_file: findings.sarif

      - name: Upload SARIF to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: findings.sarif
          
      - name: Install Endor Labs CLI
        run: |
          curl -sSfL https://get.endorlabs.com/install.sh | sh
          export PATH="$HOME/.endorctl/bin:$PATH"
      
      - name: Run manual Endor Labs scan
        run: endorctl scan --dependencies --pr
